export const SAVE_CONFIG = 'SAVE_CONFIG';
export const SAVE_CONFIG_PENDING = 'SAVE_CONFIG_PENDING';
export const SAVE_CONFIG_FULFILLED = 'SAVE_CONFIG_FULFILLED';
export const SAVE_CONFIG_REJECTED = 'SAVE_CONFIG_REJECTED';
export const LOAD_CONFIG = 'LOAD_CONFIG';
export const LOAD_CONFIG_PENDING = 'LOAD_CONFIG_PENDING';
export const LOAD_CONFIG_FULFILLED = 'LOAD_CONFIG_FULFILLED';
export const LOAD_CONFIG_REJECTED = 'LOAD_CONFIG_REJECTED';
