export const SAVE_GAME = 'SAVE_GAME';
export const SAVE_GAME_PENDING = 'SAVE_GAME_PENDING';
export const SAVE_GAME_FULFILLED = 'SAVE_GAME_FULFILLED';
export const SAVE_GAME_REJECTED = 'SAVE_GAME_REJECTED';
export const LOAD_GAME = 'LOAD_GAME';
export const LOAD_GAME_PENDING = 'LOAD_GAME_PENDING';
export const LOAD_GAME_FULFILLED = 'LOAD_GAME_FULFILLED';
export const LOAD_GAME_REJECTED = 'LOAD_GAME_REJECTED';
